### ISSUE TITLE
Is evaluation only happening for < 10,000 users?

### ISSUE THREAD

**Issue by seanswyi** [pmixer/SASRec.pytorch#34]
Hi. I was going through the code and noticed that during evaluation the number of users we evaluate on is capped at 10,000 (https://github.com/pmixer/SASRec.pytorch/blob/4297d0950c6a6bffba92ecd4d1bf7204d07eb8c7/utils.py#L116)? Is that correct?

```
if usernum>10000:
        users = random.sample(range(1, usernum + 1), 10000)
    else:
        users = range(1, usernum + 1)
    for u in users:
        ...
```

In my own implementation I looped over all users (e.g., 52K for Amazon Beauty) and divided the nDCG and hit rates by the total number of users.

I'm actually not familiar with how evaluation in recommendation systems works and am wondering if I understood correctly and if this kind of sampled evaluation is common.

Thanks.

**Comment by pmixer** [comment]
Correct, I kept it exactly same as in original paper author's tf implementation:

https://github.com/kang205/SASRec/blob/master/util.py#L47

Pls feel free to evaluate for all users as long as your compute resources can handle it.

For evalution in recommendation systems, there's no strict standard in research actually(in industry, variants of AUC(and DAU lol) most widely used), people are free to customize their own receipe sometimes, and these practices can be problematic sometimes as shown in https://www.kdd.org/kdd2020/accepted-papers/view/on-sampling-top-k-recommendation-evaluation, related issues root cause(personal guess): one can not affort ranking all items for all users all the time just for research in practice, as long as research oriented datasets are sampled results by themselves, also there're no golden rules on sampling for recsys till now. 

BTW, I plan to watch [Counterfactual Learning and Evaluation for Recommender Systems](https://www.youtube.com/watch?v=HMo9fQMVB4w) throughly but haven't yet, manual recommendation :), might be interesting.

**Comment by seanswyi** [comment]
Thanks for the paper and video, both seem interesting.

My background is actually in NLP and this is the first RecSys project that I've ever worked on. I got the same impression that evaluation may be a little more problematic when it comes to research and fair evaluation.

I'm not sure if this would be the root cause, but my own implementation is actually showing lower performance. I'd say around 4-5% for both Hit@10 and nDCG@10 on average across all four datasets.

There are a few differences I made (e.g., I'm not layer-normalizing the query input into self-attention) but I don't think that small difference would result in such a huge performance gap. Do you think that evaluating over all users may be one of the main contributors to differing performances?

**Comment by pmixer** [comment]
> Thanks for the paper and video, both seem interesting.
> 
> My background is actually in NLP and this is the first RecSys project that I've ever worked on. I got the same impression that evaluation may be a little more problematic when it comes to research and fair evaluation.
> 
> I'm not sure if this would be the root cause, but my own implementation is actually showing lower performance. I'd say around 4-5% for both Hit@10 and nDCG@10 on average across all four datasets.
> 
> There are a few differences I made (e.g., I'm not layer-normalizing the query input into self-attention) but I don't think that small difference would result in such a huge performance gap. Do you think that evaluating over all users may be one of the main contributors to differing performances?
> 
> **Edit** Ah I also forgot to mention that the way I'm handling negative sampling is also different. I noticed that you and the official SASRec authors both perform random negative sampling for 10,000 users on the fly. However, I sampled 100 random negative samples for each user during data pre-processing and continued to use the same 100 negative samples during evaluation. Would this also be causing a problem? It's very difficult to get the hang of how negative sampling should be performed since there doesn't seem to be any central resource or convention (very different from NLP lol).

may be due to the initialization phase differences, I met similar problem before, and solved in https://github.com/pmixer/SASRec.pytorch/commit/1d8aaa2dcf3837b0518692faee8af577cc166188

**Comment by seanswyi** [comment]
Ah yeah perhaps. I didn't do any explicit initialization on my parameters. I'll give it a try, thanks!
